### ISSUE TITLE
Random Connection Breakup

### ISSUE THREAD

**Issue by Alienmaster** [redis/redis-py#1457]
I'm feeding with one script on Machine A raw PCM/Wave Data in Chunks into a Redis pubsub channel.
Redis runs on Machine B.
Then reading with another script on Machine A. 
Both machines are in the same university network.

This is feeding Code **without** any errors (just for illustration):

```
def read_in_chunks(infile, chunk_size=4096*2):
    while True:
        chunk = infile.read(chunk_size)
        time.sleep(0.1)
        if chunk:
            yield chunk
        else:
            return

file = open(filename, "rb")
for chunk in read_in_chunks(file):
    red.publish("test", chunk)
```
after several Minutes working the reading Script crashs with the following Error:
```
Traceback (most recent call last):
  File "nnet3_model.py", line 731, in <module>
    decode_control_channel=args.redis_control_channel, audio_data_channel=args.redis_audio_channel)
  File "nnet3_model.py", line 411, in decode_chunked_partial_endpointing_mic
    block_audio_redis_msg = next(pa.listen())
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 363, in read_response
    response = [self.read_response() for i in xrange(length)]
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 363, in <listcomp>
    response = [self.read_response() for i in xrange(length)]
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 357, in read_response
    response = self._buffer.read(length)
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 237, in read
    self._read_from_socket(length - self.length)
  File "/home/6geislin/kaldi-model-server/kms_env/lib/python3.7/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
```
I tried to change the chunk size to 2*2048 or the sleep time to 50ms but the result is the same.

Update: When i use 4096*2 as Chunksize and 140ms Sleeptime it works.

**Version**: 3.5.3

**Platform**: Python 3.7.9 on Ubuntu 18.0.45 LTS

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

**Comment by Alienmaster** [comment]
Hi,
the solution for me was to use [time.sleep](https://github.com/uhh-lt/bbb-live-subtitles/blob/main/kaldi_starter.py#L36). This prevented the issue for me. It is not the most beautiful solution but it works :)
