### ISSUE TITLE
PubSub does not auto-reconnect with listen()

### ISSUE THREAD

**Issue by luhn** [redis/redis-py#1573]
Version: redis-py 3.5.3, redis 6.2.5

Platform: Python 3.9.6 on MacOS

On the surface this looks like a duplicate of #1572, but the stack traces are completely different.

However, the docs hint that listen() is deprecated?  Feel free to close this issue if thats the case.

Anyways, same deal as #1572.  Stop the Redis server, then start it again, I'd expect to auto-reconnect but it doesn't.  Here's the script:

```python
import redis
import itertools
import threading
from time import sleep


class PubSubWorkerThread(threading.Thread):
    def __init__(self, pubsub, sleep_time, daemon=False):
        super(PubSubWorkerThread, self).__init__()
        self.daemon = daemon
        self.pubsub = pubsub
        self.sleep_time = sleep_time
        self._running = threading.Event()

    def run(self):
        if self._running.is_set():
            return
        self._running.set()
        pubsub = self.pubsub
        sleep_time = self.sleep_time
        while self._running.is_set():
            try:
                for message in pubsub.listen():
                    print(message)
            except Exception:
                print('listen failed')
                sleep(2)
        pubsub.close()

    def stop(self):
        # trip the flag so the run loop exits. the run loop will
        # close the pubsub connection, which disconnects the socket
        # and returns the connection to the pool.
        self._running.clear()


redis = redis.Redis()
pubsub = redis.pubsub()
pubsub.subscribe('topic')

thread = PubSubWorkerThread(pubsub, 1)
thread.start()

for i in itertools.count():
    try:
        redis.publish('topic', str(i))
    except Exception:
        print('publish failed')
    sleep(1)
```

Expected behavior: Publish and get_message will fail while Redis is stopped, then resume working when Redis is started.

Observed behavior: After restarting Redis, publish resumes working, get_message continues to fail.

Here's the stack trace:

```
Traceback (most recent call last):
  File "/Users/luhn/Code/redis-py/test2.py", line 24, in run
    for message in pubsub.listen():
  File "/Users/luhn/Code/redis-py/redis/client.py", line 3605, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/Users/luhn/Code/redis-py/redis/client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/Users/luhn/Code/redis-py/redis/client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "/Users/luhn/Code/redis-py/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/Users/luhn/Code/redis-py/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```

**Comment by romainsacchi** [comment]
Having the same issue. Any fix for this?

**Comment by luhn** [comment]
I'm not sure if `listen` is recommended anymore.  I loop over `get_message`, which should work in the latest version.  (See #1572)

**Comment by chayim** [comment]
Concur. Please see @luhn great PR and change, which you can find, starting in redis-py 4.0.0.
