### ISSUE TITLE
execute_command() can not seem to accept the value, if the value string has a space in it.

### ISSUE THREAD

**Issue by ghost** [redis/redis-py#1659]
**Version**: redis-py version 3.5.3, redis-cli version 5.0.7

**Platform**: Python 3.10.0, Linux latitude 5.11.0-38-lowlatency #42~20.04.1-Ubuntu SMP PREEMPT Tue Sep 28 21:54:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description**: If there are spaces in the value string, execute_command will not accept, constantly saying there is a syntax error.  Seems that the quotes housing the spaces-including string are getting lost, and Redis interprets it as extra arguments on the SET command.  Thank for reading!

--------------------

\>>> r = redis.Redis(host='localhost', port=6379, db=0)
\>>> r.execute_command('SET myLongString_1 "hello there"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: syntax error
\>>> r.execute_command('SET myLongString_1 \"hello there\"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: syntax error
\>>> r.execute_command("SET myLongString_1 'hello there'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: syntax error
\>>> r.execute_command("SET myLongString_1 \"hello there\"")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/imjimcap/.local/share/virtualenvs/cindi-ucx_oYAP/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: syntax error
\>>> r.set("myLongString_1", "hello there")
True
\>>>

**Comment by chayim** [comment]
Hi @imjimcap, thanks for reporting this.  So, the execute_command isn't designed to work this way. Taking a look at the function signature we expect a list and dictionary (*args, **kwargs). The [helper function for this command](https://github.com/redis/redis-py/blob/599f5a991eda770799a1aea23848b1442019deeb/redis/commands/core.py#L1126) actively adds things to a list accordingly.

In general, the goal is to provide command parity with Redis, meaning there ought be helper functions for each interaction. I recommend trying those!

I've added the feature label, so that we don't lose track of this, and consider it for upcoming releases. Thanks again!

**Comment by imjimcap** [comment]
Chayim,

Thanks for the insight.  I simply am trying to use it with a tool that
generates Redis commands, so it's convenient to be able to pass the exact
command directly.  Thank you for adding the feature label and clarifying to
me how to use the library!

Jim

**Comment by chayim** [comment]
@imjimcap Any time! We'll leave this open, because I can definitely understand the value in a _raw_ mode, or something like it.  But as long as you're unblocked I'm happy! Be sure to link the tool in here later, if it's open source. I'd love to see it.

**Comment by annihilatorrrr** [comment]
this issue isn't solved yet ?
i tried this and got this error:
> REDIS = Redis.from_url(REDIS_URL, decode_responses=True)
`await REDIS.set(1111, "ok", ex=15, keepttl=True)`
