### ISSUE TITLE
UnicodeDecodeError 

### ISSUE THREAD

**Issue by korsar182** [redis/redis-py#1891]
**Version**: 4.1.1

**Platform**: python 3.9 on Linux

**Description**: 
from django.core.cache import cache
cache.set('a','b')
True
cache.get('a')
Traceback (most recent call last):
File "", line 1, in
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
value = self._get(key, default, version, client)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
return method(self, *args, **kwargs)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
return self.client.get(key, default=default, version=version, client=client)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
value = client.get(key)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/commands/core.py", line 1233, in get
return self.execute_command("GET", name)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1176, in execute_command
return conn.retry.call_with_retry(
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/retry.py", line 41, in call_with_retry
return do()
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1177, in
lambda: self._send_command_parse_response(
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1153, in _send_command_parse_response
return self.parse_response(conn, command_name, **options)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1192, in parse_response
response = connection.read_response()
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 800, in read_response
response = self._parser.read_response(disable_decoding=disable_decoding)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 364, in read_response
response = self.encoder.decode(response)
File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 124, in decode
value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Seems redis doesn't work on python 3.9.

**Comment by korsar182** [comment]
Sorry, just wrong setting decode_responses=True
