### ISSUE TITLE
4.1.4 redis.exceptions.ConnectionError. Error 110. Connection timed out

### ISSUE THREAD

**Issue by Sj1218305** [redis/redis-py#2034]
**Version**: 
Python 3.7
Redis: 6.x (GCP Redis)
Redis-py: 4.1.4
Flask: 1.0.2

**Description**: 
Hello Team,

We are facing an issue while hitting the redis apis on a deployed container.
I am trying to add data to redis as key-value pair and also setting expiration period for the same
When I hit the apis from my local then, everything worked fine. 
But when I deployed the microservice on Cloud Run, and hit the required api, it's giving the following error ⬇️ 

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/__handlers__.py", line 52, in __call__
    response = self.function(*args, **kwargs)
  File "/app/app.py", line 343, in local_upload_to_gcs
    files = uploader_app.uploadToLocal(files)
  File "/app/api_uploader.py", line 432, in uploadToLocal
    set_cache.set_ttl(self.dataset_id, config.EXPIRATION_PERIOD)
  File "/app/cache_service.py", line 17, in set_ttl
    self.db.expire(name=key, time=ttl)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1192, in expire
    return self.execute_command('EXPIRE', name, time)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to 10.137.211.155:6379. Connection timed out
```
During handling of the above exception, another exception occurred:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out
```
Thanks a lot.

**Comment by chayim** [comment]
@Sj1218305 have you tried both upping the timeouts and ensuring that you can connect to the instance you have at 10.137.211.155 at port 6379 using redis-cli? I'd like to identify if this is a library issue, or something else?

**Comment by Sj1218305** [comment]
@chayim , I have solved this error. It's not the library issue.
GCP redis managed service needs a VPC access connector to set up connection with a service deployed on Cloud Run. 
https://cloud.google.com/memorystore/docs/redis/supported-environments#serverless-environments-that-need-a-serverless-vpc-access-connector
