### ISSUE TITLE
slowlog_get() fails with TypeError, regression going from 4.1.4 to 4.2.2

### ISSUE THREAD

**Issue by papakipos** [redis/redis-py#2085]
**Version**: python redis 4.2.2
The bug was NOT present in 4.1.4.
This is a regression.

**Platform**: Azure python 3.8.13 (though I doubt this is Azure-related)

**Description**: 

Today was the first time I've ever seen this problem. Today was the day I upgraded to python redis 4.2.2. I've verified that the problem does not exist in 4.1.4 (so I will downgrade my development & production environment again).

client.py:parse_slowlog_get() is failing on the last line here:
        if isinstance(item[3], list):
            result["command"] = space.join(item[3])

with this error message:
        "TypeError: sequence item 0: expected str instance, bytes found"

Redis runtime environment:
       Redis is running on Redis Enterprise, hosted on AWS by Redis Labs.  
       Redis version 6.2.3.

Python stack trace. Note error message at the end.
Traceback (most recent call last):
  File "/Users/Matt/Finance/python/shared_code/monitor_time.py", line 507, in <module>
    monitor_time()
  File "/Users/Matt/Finance/python/shared_code/monitor_time.py", line 166, in monitor_time
    redis_client.slowlog_get(slowlog_max_length, decode_responses=True)
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/commands/core.py", line 1135, in slowlog_get
    return self.execute_command(*args, **kwargs)
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 1218, in execute_command
    return conn.retry.call_with_retry(
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 1219, in <lambda>
    lambda: self._send_command_parse_response(
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 1195, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 1240, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 428, in parse_slowlog_get
    return [parse_item(item) for item in response]
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 428, in <listcomp>
    return [parse_item(item) for item in response]
  File "/Users/Matt/.pyenv/versions/3.8.13/lib/python3.8/site-packages/redis/client.py", line 422, in parse_item
    result["command"] = space.join(item[3])
TypeError: sequence item 0: expected str instance, bytes found

**Comment by papakipos** [comment]
I determined that dropping the decode_responses=True argument from my slowlog_get() call made the problem go away. Issue resolved.
