### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'ZPOPMIN'

### ISSUE THREAD

**Issue by mikolaje** [redis/redis-py#2117]
Versions:
```
Ubuntu 18
redis                              4.2.2
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3
```

Traceback:
```
Traceback (most recent call last):
  File "group_clearance_bot.py", line 55, in <module>
    clear_command_msg_redis()
  File "group_clearance_bot.py", line 33, in clear_command_msg_redis
    msg_item = conn.zpopmin('msg_list')[0]
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/commands/core.py", line 4067, in zpopmin
    return self.execute_command("ZPOPMIN", name, *args, **options)
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1222, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1220, in <lambda>
    conn, command_name, *args, **options
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1195, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/client.py", line 1234, in parse_response
    response = connection.read_response()
  File "/opt/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 836, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'ZPOPMIN'
```

**Comment by WisdomPill** [comment]
This command is available since `redis` 5.0.0, you are using version 4.2.2

@chayim is there some plan to implement version check at the connection time?
So that commands will not be sent if they are not supported by the server.

Is there a simple way to find out about `redis-server` version without parsing `INFO server` command?
But most importantly, can a cluster run with different versions? Like during a rolling update

**Comment by mikolaje** [comment]
Thank you, just update Redis to the latest version to work around.

**Comment by WisdomPill** [comment]
Please reopen, a good improvement could come up from this issue

**Comment by chayim** [comment]
I don't think the client, on its connection should validate the version of redis. What that does is slow down the client - or at least the connection (then multiply in pools and clusters... what about autoscaling!). We do have a mechanism for this, with the connection functions - should someone want to implement - and I'd happily read that or any similar PR that we can use.

Please feel free to open a dedicated issue for redis version (and command) adherence checking.
