### ISSUE TITLE
redis.asyncio module import error

### ISSUE THREAD

**Issue by jtr216** [redis/redis-py#2221]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on? 4.3.3

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure) Python 3.10 os 11.6.6, PyCharm 2022.1.2

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

`import redis.asyncio` works, but displays a "No Module named 'asyncio'" error in pycharm and does not provide autocomplete.  Is this expected ? 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/29043017/172463177-15e50c98-da3d-4826-bdaa-0a5489672357.png">

**Comment by Olegt0rr** [comment]
It's a pyCharm's issue.

Use:
`Pycharm -> File -> Invalidate Caches`

**Comment by sunhailin-Leo** [comment]
> 

I try it, but it doesn`t work. (PyCharm 2022.2，Python 3.7)

**Comment by Olegt0rr** [comment]
@sunhailin-Leo , use workaround: https://github.com/redis/redis-py/issues/2249#issuecomment-1172943002

**Comment by genagurbanguliyev** [comment]
Thanks!

**Comment by shikha12264** [comment]
Am facing similar issue on Visual Studio Code!
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/computron/src/app.py", line 5, in <module>
    from pyfit.server import ServerConfig
  File "/.venv/lib/python3.8/site-packages/pyfit/__init__.py", line 17, in <module>
    from pyfit.db import MongoConnection
  File "/.venv/lib/python3.8/site-packages/pyfit/db/__init__.py", line 7, in <module>
    from .redis_conn import RedisConnection
  File "/.venv/lib/python3.8/site-packages/pyfit/db/redis_conn.py", line 6, in <module>
    import redis.asyncio as aredis
  File "/.venv/lib/python3.8/site-packages/redis/asyncio/__init__.py", line 1, in <module>
    from redis.asyncio.client import Redis, StrictRedis
  File "/.venv/lib/python3.8/site-packages/redis/asyncio/client.py", line 27, in <module>
    from redis._parsers.helpers import (
  File "/.venv/lib/python3.8/site-packages/redis/_parsers/__init__.py", line 1, in <module>
    from .base import BaseParser, _AsyncRESPBase
  File "/.venv/lib/python3.8/site-packages/redis/_parsers/base.py", line 11, in <module>
    from ..exceptions import (
ImportError: cannot import name 'ModuleError' from 'redis.exceptions' (/.venv/lib/python3.8/site-packages/redis/exceptions.py)
```

**Comment by jagdishwar** [comment]
Yes facing similar issues on VScode.

**Comment by Olegt0rr** [comment]
> Am facing similar issue on Visual Studio Code!

It's not a similar error. Create a new issue.

**Comment by shivank22** [comment]
For VSCode downgrade to redis 3.5 FastAPI is not compatible with redis5.0 
I downgraded and then it worked
