### ISSUE TITLE
`redis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server`

### ISSUE THREAD

**Issue by justinTM** [redis/redis-py#2250]
**Version**: `4.3.3`

**Platform**: Databricks 10.4.x-aarch64-scala2.12

**Description**:

```python
[2022-06-24T16:25:53.692617][DatasetDeleter][key_prefix='{myjob}'] finished deleting. Summary: {'count of keys deleted': 0, 'count of calls to pipe.delete()': 0, 'seconds elapsed': 0.802898645401001, 'keys per second': 0}
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
     96 
     97   try:
---> 98     myjob()
     99   except Exception as e:
    100     if "Path does not exist" in str(e):

/tmp/tmp1m_cpmmp.py in myjob()
     62     delete(mcr.myjob.writer.key_prefix)
     63     # mcr.delete_dataset(mcr.myjob)
---> 64     df_myjob.foreachPartition(foreachPartition_myjob)
     65 
     66     elapsed_s = time.time() - time_start

/databricks/spark/python/pyspark/sql/dataframe.py in foreachPartition(self, f)
    816         >>> df.foreachPartition(f)
    817         """
--> 818         self.rdd.foreachPartition(f)
    819 
    820     def cache(self):

/databricks/spark/python/pyspark/rdd.py in foreachPartition(self, f)
    938             except TypeError:
    939                 return iter([])
--> 940         self.mapPartitions(func).count()  # Force evaluation
    941 
    942     def collect(self):

/databricks/spark/python/pyspark/rdd.py in count(self)
   1267         3
   1268         """
-> 1269         return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
   1270 
   1271     def stats(self):

/databricks/spark/python/pyspark/rdd.py in sum(self)
   1256         6.0
   1257         """
-> 1258         return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
   1259 
   1260     def count(self):

/databricks/spark/python/pyspark/rdd.py in fold(self, zeroValue, op)
   1110         # zeroValue provided to each partition is unique from the one provided
   1111         # to the final reduce call
-> 1112         vals = self.mapPartitions(func).collect()
   1113         return reduce(op, vals, zeroValue)
   1114 

/databricks/spark/python/pyspark/rdd.py in collect(self)
    964         # Default path used in OSS Spark / for non-credential passthrough clusters:
    965         with SCCallSiteSync(self.context) as css:
--> 966             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    967         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    968 

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 14) (10.25.213.148 executor 0): org.apache.spark.api.python.PythonException: 'redis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server: [host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,name=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com:6379,server_type=None,redis_connection=Redis<ConnectionPool<SSLConnection<host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,db=0>>>]. error: Accessed keys are unavailable to be served'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1474, in initialize
    if bool(r.info().get("cluster_enabled")) is False:
  File "/databricks/python/lib/python3.8/site-packages/redis/commands/core.py", line 964, in info
    return self.execute_command("INFO", **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
    return conn.retry.call_with_retry(
  File "/databricks/python/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1236, in <lambda>
    lambda: self._send_command_parse_response(
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1212, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1251, in parse_response
    response = connection.read_response()
  File "/databricks/python/lib/python3.8/site-packages/redis/connection.py", line 837, in read_response
    raise response
redis.exceptions.ResponseError: Accessed keys are unavailable to be served

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 752, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 742, in process
    out_iter = func(split_index, iterator)
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 418, in func
    return f(iterator)
  File "/databricks/spark/python/pyspark/rdd.py", line 935, in func
    r = f(it)
  File "/tmp/tmp1m_cpmmp.py", line 19, in foreachPartition_myjob
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 596, in __init__
    self.nodes_manager = NodesManager(
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1299, in __init__
    self.initialize()
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1497, in initialize
    raise RedisClusterException(
redis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server: [host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,name=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com:6379,server_type=None,redis_connection=Redis<ConnectionPool<SSLConnection<host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,db=0>>>]. error: Accessed keys are unavailable to be served

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:694)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:904)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:886)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:647)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1038)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2984)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2931)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2925)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2925)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1345)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3193)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3134)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3122)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1107)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2637)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1036)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:419)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1034)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:260)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: 'redis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server: [host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,name=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com:6379,server_type=None,redis_connection=Redis<ConnectionPool<SSLConnection<host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,db=0>>>]. error: Accessed keys are unavailable to be served'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1474, in initialize
    if bool(r.info().get("cluster_enabled")) is False:
  File "/databricks/python/lib/python3.8/site-packages/redis/commands/core.py", line 964, in info
    return self.execute_command("INFO", **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
    return conn.retry.call_with_retry(
  File "/databricks/python/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1236, in <lambda>
    lambda: self._send_command_parse_response(
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1212, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/databricks/python/lib/python3.8/site-packages/redis/client.py", line 1251, in parse_response
    response = connection.read_response()
  File "/databricks/python/lib/python3.8/site-packages/redis/connection.py", line 837, in read_response
    raise response
redis.exceptions.ResponseError: Accessed keys are unavailable to be served

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 752, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 742, in process
    out_iter = func(split_index, iterator)
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 2952, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/databricks/spark/python/pyspark/rdd.py", line 418, in func
    return f(iterator)
  File "/databricks/spark/python/pyspark/rdd.py", line 935, in func
    r = f(it)
  File "/tmp/tmp1m_cpmmp.py", line 19, in foreachPartition_myjob
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 596, in __init__
    self.nodes_manager = NodesManager(
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1299, in __init__
    self.initialize()
  File "/databricks/python/lib/python3.8/site-packages/redis/cluster.py", line 1497, in initialize
    raise RedisClusterException(
redis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server: [host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,name=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com:6379,server_type=None,redis_connection=Redis<ConnectionPool<SSLConnection<host=clustercfg.mycluster.memorydb.us-east-1.amazonaws.com,port=6379,db=0>>>]. error: Accessed keys are unavailable to be served

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:694)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:904)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:886)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:647)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1038)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by chayim** [comment]
Hi @justinTM what version of redis are you using? Is it in cluster mode? Can you help us help youi?

**Comment by justinTM** [comment]
hi @chayim I believe the cluster was out of memory and refusing to process requests
