### ISSUE TITLE
 consumer: Cannot connect to redis://127.0.0.1:8000/2: .

### ISSUE THREAD

**Issue by blackskymoonstar** [redis/redis-py#2337]
Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 789, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 249, in readline
    self._read_from_socket()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 623, in connect
    self.on_connect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 734, in on_connect
    if str_if_bytes(self.read_response()) != "OK":
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 832, in read_response
    self.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 496, in _on_connection_disconnect
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 464, in __init__
    self.client.info()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 920, in client
    return self._create_client(asynchronous=True)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 873, in _create_client
    return self.AsyncClient(connection_pool=self.async_pool)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 894, in __init__
    self.connection = self.connection_pool.get_connection('_')
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1387, in get_connection
    connection.connect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 629, in connect
    self.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 496, in _on_connection_disconnect
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 449, in _ensured
    return fun(*args, **kwargs)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\messaging.py", line 177, in _publish
    channel = self.channel
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 771, in default_channel
    self.connection
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 466, in __init__
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 789, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 249, in readline
    self._read_from_socket()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 623, in connect
    self.on_connect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 734, in on_connect
    if str_if_bytes(self.read_response()) != "OK":
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 832, in read_response
    self.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 496, in _on_connection_disconnect
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 464, in __init__
    self.client.info()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 920, in client
    return self._create_client(asynchronous=True)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 873, in _create_client
    return self.AsyncClient(connection_pool=self.async_pool)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 894, in __init__
    self.connection = self.connection_pool.get_connection('_')
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1387, in get_connection
    connection.connect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 629, in connect
    self.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 496, in _on_connection_disconnect
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/PythonDjangoproject/Django/view4/produce_task.py", line 3, in <module>
    result = send_email.delay("yuan")
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\celery\app\task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\celery\app\task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\celery\app\base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\celery\app\amqp.py", line 310, in publish_task
    **kwargs
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 470, in _ensured
    interval_max)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\utils\__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 250, in connect
    return self.connection
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\virtual\__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 466, in __init__
    self._disconnect_pools()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 484, in _disconnect_pools
    self._async_pool.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 1466, in disconnect
    connection.disconnect()
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 866, in disconnect
    channel._on_connection_disconnect(self)
  File "C:\Users\86130\AppData\Local\Programs\Python\Python37\lib\site-packages\kombu\transport\redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError

**Comment by blackskymoonstar** [comment]
Ask for help, provide a little idea that can't connect redis

**Comment by blackskymoonstar** [comment]
this problem is resolved
