### ISSUE TITLE
redis.exceptions.ResponseError: wrong number of arguments for 'hset' command

### ISSUE THREAD

**Issue by Leventi** [redis/redis-py#2355]
When try add dict to redis got error

**Version**:
Server redis_version:3.0.504
Redis on WSL Ubuntu
Installed by docs https://redis.io/docs/getting-started/installation/install-redis-on-windows/

```
alex@WP-07:~$ apt-cache policy info redis
info:
  Installed: 6.7.0.dfsg.2-5
  Candidate: 6.7.0.dfsg.2-5
  Version table:
 *** 6.7.0.dfsg.2-5 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
redis:
  Installed: 6:7.0.4-1rl1~focal1
  Candidate: 6:7.0.4-1rl1~focal1
  Version table:
 *** 6:7.0.4-1rl1~focal1 500
        500 https://packages.redis.io/deb focal/main amd64 Packages
        500 https://packages.redis.io/deb focal/main all Packages
        100 /var/lib/dpkg/status
```

**Lib version**: redis 4.3.4

**Platform**: 
Python 3.10 on Windows 10

**Code where trouble**:
```
import redis

r1 = redis.Redis(host='127.0.0.1', port=6379, db=0)

email_validate = {
   "total": 17,
   "daily": 3,
   "valid": 23.53,
   "possibly_valid": 23.53,
   "risky": 11.76,
   "invalid": 41.18
}

r1.hset('email_validate_r', mapping=email_validate)

# try this too
# r1.hset('email_validate_r', **email_validate)

```

**Error**
```
Traceback (most recent call last):
  File "C:\Users\user\dev\redis_test_prj\redis_test.py", line 22, in <module>  
  r1.hset('email_validate_r', mapping=email_validate)
  File "C:\Users\user\dev\venv\lib\site-packages\redis\commands\core.py", line 4841, in hset
    return self.execute_command("HSET", name, *items)
  File "C:\Users\user\dev\venv\lib\site-packages\redis\client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "C:\Users\user\dev\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\user\dev\venv\lib\site-packages\redis\client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "C:\Users\user\dev\venv\lib\site-packages\redis\client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\user\dev\venv\lib\site-packages\redis\client.py", line 1254, in parse_response
    response = connection.read_response()
  File "C:\Users\user\dev\venv\lib\site-packages\redis\connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'hset' command
```

**Comment by dvora-h** [comment]
As you mentioned your server version is 3.0.5 while the option to send multiple `field` and `value` arguments was added just in 4.0.0.
Redis-py only supports redis 4.X and above

**Comment by Leventi** [comment]
It's very strange
When I checking in terminal then got
```
alex@WP-07:~$ redis-server -v
Redis server v=7.0.4 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=c7d71d4b63066c
````

If checking from redis-cli got
```
127.0.0.1:6379> info
# Server
redis_version:3.0.504
```

When trying in terminal `sudo service redis-server start`
Got
```
alex@WP-07:~$ sudo /etc/init.d/redis-server status
 * redis-server is not running
```

But `redis-cli` working and I can write data to database but can't using `mapping`
