### ISSUE TITLE
Vector similarity search Syntax error

### ISSUE THREAD

**Issue by lolleko** [redis/redis-py#2375]
**Version**:
- redis-py=4.3.4
- redis-stack-server=latest

**Platform**: 
- redis-py on windows client
- redis-stack-server in docker container on ubuntu server

**Description**: 

I am getting an: `redis.exceptions.ResponseError: Syntax error at offset 1 near >[` Error when using `ft().search(/*KNN*/)`

I get this error as well, when I run the test case from this repo(https://github.com/redis/redis-py/blob/master/tests/test_search.py#L1548
).
In addition I have no problems running `FT.SEARCH` queries via `redis-cli`. So I don't think my usage is the issue.

REPRO:

```
import redis

from redis.commands.search.field import VectorField
from redis.commands.search.query import Query

r = redis.Redis(host='localhost', port=6379)

r.flushdb()
r.ft().create_index(
    (
        VectorField(
            "v", "HNSW", {"TYPE": "FLOAT32", "DIM": 2, "DISTANCE_METRIC": "L2"}
        ),
    )
)
r.hset("a", "v", "aaaaaaaa")
r.hset("b", "v", "aaaabaaa")
r.hset("c", "v", "aaaaabaa")

q = Query("*=>[KNN 2 @v $vec]").return_field("__v_score").sort_by("__v_score", True)
res = r.ft().search(q, query_params={"vec": "aaaaaaaa"})
```
<details>
  <summary>[TRACE]</summary>
  
```
Traceback (most recent call last):
  File "c:/Users/lolleko/Repos/MasterThesis/Backend/Server/load_images_into_db.py", line 37, in <module>
    res = r.ft().search(q, query_params={"vec": "aaaaaaaa"})
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\commands\search\commands.py", line 412, in search
    res = self.execute_command(SEARCH_CMD, *args)
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\client.py", line 1254, in parse_response
    response = connection.read_response()
  File "C:\Users\lolleko\anaconda3\envs\thesis\lib\site-packages\redis\connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: Syntax error at offset 1 near >[
```
</details>

**Comment by dvora-h** [comment]
@lolleko To use a vector similarity query, you must specify the DIALECT 2
```
q = Query("*=>[KNN 2 @v $vec]").return_field("__v_score").sort_by("__v_score", True).dialect(2)
```

https://redis.io/docs/stack/search/reference/vectors/#querying-vector-fields
