### ISSUE TITLE
Redis no longer retrying on ConnectionError

### ISSUE THREAD

**Issue by Kaiyotech** [redis/redis-py#2427]
**Version**: redis-py 4.3.4, redis 6.2.6

**Platform**: Python 3.9 for the redis-py on Windows, WSL2 for redis on another Windows machine.

**Description**: This worked previously, but suddenly one day it stopped working, despite nothing changing in my code or on my machine. My remote machines which are contributing/reading from redis using redis-py have stopped respecting the retry on TimeoutError and ConnectionError that I've set. Trace is below, code is below that. You can see that redis.exceptions.ConnectionError should be retried, yet it's in the bottom of the stack trace.

`Traceback (most recent call last):
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\connection.py", line 249, in readline
    self._read_from_socket()
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\connection.py", line 192, in _read_from_socket
    data = self._sock.recv(socket_read_size)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Code\username\project\worker.py", line 103, in <module>
    RedisRolloutWorker(r, name, match,
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\rocket_learn\rollout_generator\redis\redis_rollout_worker.py", line 394, in run
    n_items = self.red_pipe.execute()
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 2078, in execute
    return conn.retry.call_with_retry(
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\retry.py", line 49, in call_with_retry
    fail(error)
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 2080, in <lambda>
    lambda error: self._disconnect_raise_reset(conn, error),
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 2079, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 1943, in _execute_transaction
    self.parse_response(connection, "_")
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 2018, in parse_response
    result = Redis.parse_response(self, connection, command_name, **projectons)
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\client.py", line 1254, in parse_response
    response = connection.read_response()
  File "C:\Users\user\Code\username\project\venv\lib\site-packages\redis\connection.py", line 830, in read_response
    raise ConnectionError(f"Error while reading from {hosterr}" f" : {e.args}")
redis.exceptions.ConnectionError: Error while reading from 192.168.0.204:6379 : (10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)`

`from redis import Redis
from redis.retry import Retry
from redis.backoff import ExponentialBackoff
from redis.exceptions import ConnectionError, TimeoutError`

`r = Redis(host=host,
                  username="user1",
                  password=os.environ["redis_user1_key"],
                  retry_on_error=[ConnectionError, TimeoutError],
                  retry=Retry(ExponentialBackoff(cap=10, base=1), 25),
                  db=Constants.DB_NUM,
                  )`

**Comment by Kaiyotech** [comment]
This is still occurring, I can't find a resolution.

**Comment by Artimi** [comment]
I can confirm that this is also happening for `redis.asyncio.RedisCluster`.
When the connection is closed (e.g. because of `ClusterDownError`) I get this error right away. The `initialize()` is not retried regardless on `connection_error_retry_attempts` option.
```
'Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/connection.py", line 600, in connect
    await self.retry.call_with_retry(
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/connection.py", line 637, in _connect
    reader, writer = await asyncio.open_connection(
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('173.18.0.21', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/cluster.py", line 662, in execute_command
    await self.initialize()
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/cluster.py", line 370, in initialize
    await self.commands_parser.initialize(
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/parser.py", line 34, in initialize
    commands = await self.node.execute_command("COMMAND")
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/cluster.py", line 1002, in execute_command
    await connection.send_packed_command(connection.pack_command(*args), False)
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/connection.py", line 770, in send_packed_command
    await self.connect()
  File "/opt/venv/lib/python3.9/site-packages/redis/asyncio/connection.py", line 608, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 173.18.0.21:6379. 111.'

```

**Comment by Artimi** [comment]
@Kaiyotech I suggest you to try with the newest `redis-py` version 4.5.3. I wasn't checking exactly this but the connection seems much more stable when I try to kill nodes in redis cluster.

**Comment by geonyoro** [comment]
I can confirm that this issue still exists. One of the my redis servers twice a day does a load from memory and so causes a BusyLoadingError. Redis doesn't seem to support this, or the connection Error, despite passing retries with an exponentialBackOff.

**Comment by jarviliam** [comment]
This issue is still present. If you specifically specify the os ConnectionError in the `retry_on_error` it will use the retry as expected. The problem with it is that the retry_on_error is typed to only accept RedisExceptions.

Its pretty confusing as the library exposes a ConnectionError exception, not sure if this was meant to also wrap the stdlib ConnectionError or not.
