### ISSUE TITLE
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

### ISSUE THREAD

**Issue by LookInFuture** [redis/redis-py#2561]
**Version**: Docker image redis:6.0.9

**Description**: Can't connect to local redis and get this error when start Django Project:

```
trade_1            | Internal Server Error: /ru/
trade_1            | Traceback (most recent call last):
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 32, in _decorator
trade_1            |     return method(self, *args, **kwargs)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 80, in get
trade_1            |     return self.client.get(key, default=default, version=version,
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_redis/client/default.py", line 205, in get
trade_1            |     raise ConnectionInterrupted(connection=client, parent=e)
trade_1            | django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
trade_1            |
trade_1            | During handling of the above exception, another exception occurred:
trade_1            |
trade_1            | Traceback (most recent call last):
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 35, in inner
trade_1            |     response = get_response(request)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 93, in __call__
trade_1            |     response = self.process_request(request)
trade_1            |   File "/trade/applications/webapp/middleware.py", line 120, in process_request
trade_1            |     if 'm' not in domain and (request.user_agent.is_mobile or request.user_agent.is_tablet):
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 215, in inner
trade_1            |     self._setup()
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 349, in _setup
trade_1            |     self._wrapped = self._setupfunc()
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_user_agents/middleware.py", line 17, in <lambda>
trade_1            |     request.user_agent = SimpleLazyObject(lambda: get_user_agent(request))
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_user_agents/utils.py", line 50, in get_user_agent
trade_1            |     user_agent = cache.get(key)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 39, in _decorator
trade_1            |     raise e.parent
trade_1            |   File "/usr/local/lib/python3.9/site-packages/django_redis/client/default.py", line 203, in get
trade_1            |     value = client.get(key)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1606, in get
trade_1            |     return self.execute_command('GET', name)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
trade_1            |     conn = self.connection or pool.get_connection(command_name, **options)
trade_1            |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
trade_1            |     connection.connect()
trade_1            |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
trade_1            |     raise ConnectionError(self._error_message(e))
trade_1            | redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

In settings.py I have following:
```
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env.str('REDIS_URL', default='redis://127.0.0.1:6379/0'),
    }
}
```

Didn't find any answer on how to handle it, please help!

**Comment by LookInFuture** [comment]
I finally figured it out, just in case if someone would need this:

In docker-compose.yml I have following instructions:
```
redis-qoovee:
    image: redis:6.0.9
    restart: always
    ports:
      - "6379:6379"

```

Note the name: redis-qoovee. 

Then in settings.py I changed this:

```
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env.str('REDIS_URL', default='redis://redis-qoovee/0'),
    }
}
```
So instead of `redis://127.0.0.1:6379/0` I put `redis://redis-qoovee/0`.

So in this case Django could reach redis container.

Hope it'll help someone!
