### ISSUE TITLE
Closing a listening PubSub causes a NoneType AttributeError

### ISSUE THREAD

**Issue by process** [redis/redis-py#2567]
**Version**: redis-py 4.4.2

**Platform**: Python 3.8.10, Ubuntu 22.04.5

**Description**:
If a PubSub is closed from another thread while listening, the call to listen() throws AttributeError, instead of ConnectionError. I would expect that redis-py would never throw AttributeError from accessing None.

The following code repros the issue, for a local Redis on 6379:

```
from threading import Thread
import time

import redis
import redis.exceptions

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
_redis_client = redis.Redis(connection_pool=pool)
pubsub = _redis_client.pubsub()
pubsub.psubscribe(**{'*': lambda x: x})

def listen():
    try:
        for message in pubsub.listen():
            pass
    except redis.exceptions.ConnectionError:
        print("Connection was closed.")

Thread(target=listen).start()
time.sleep(1)
pubsub.close()
```

On redis-py 4.4.0, this prints "Connection was closed."
On redis-py 4.4.2, it raises an AttributeError:

```
Traceback (most recent call last):
  <snipped :)>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/client.py", line 1529, in try_read
    return conn.read_response()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 848, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 337, in read_response
    self._buffer.rewind(pos)
AttributeError: 'NoneType' object has no attribute 'rewind'
```

Looks like its from [this commit](https://github.com/redis/redis-py/commit/a9ef0c5d0080bd14e2f189d7f31d83e758346a8d)

Some context: We use a gevent green thread to listen() for new pubsub messages. It wakes up when there's new data on the socket. Eventually, during a process shutdown, we call pubsub.close() elsewhere.

**Comment by process** [comment]
Update to this:
Since 5.0.0, the testcase above throws ValueError. The library does throw a ConnectionError internally now, but it doesn't bubble up to the caller.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  <snipped>
  File "/usr/local/lib/python3.8/dist-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.8/dist-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.8/dist-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.8/dist-packages/redis/_parsers/socket.py", line 90, in _read_from_socket
    buf.seek(current_pos)
ValueError: I/O operation on closed file.
```

**Comment by rushilsrivastava** [comment]
I believe this should be reopened
