### ISSUE TITLE
Invoke tests automatically fail with "Bind for 0.0.0.0:6378 failed: port is already allocated"

### ISSUE THREAD

**Issue by aksinha334** [redis/redis-py#2625]
**Version**: 
4.5.1

**Platform**: 
Python3.10, In Windows10 using Ubuntu 22.04 in WSL

**Description**:  
invoke tests command is failing most of the time with "Bind for 0.0.0.0:6378 failed: port is already allocated"

I have checked there's no process using that port and redis server is not running on default port. It seems it tries to allocate port 6378 twice and fails.

`___________________________________ summary ____________________________________
  linters: commands succeeded
  congratulations :)
Starting Redis tests
GLOB sdist-make: /home/aksinha/github/redis-py/setup.py
standalone-plain inst-nodeps: /home/aksinha/github/redis-py/.tox/.tmp/package/7/redis-4.5.1.zip
standalone-plain installed: astor==0.8.1,async-timeout==4.0.2,attrs==22.2.0,black==22.3.0,certifi==2022.12.7,charset-normalizer==3.1.0,click==8.0.4,coverage==7.2.1,distlib==0.3.6,docker==5.0.3,exceptiongroup==1.1.1,filelock==3.9.1,flake8==5.0.4,flynt==0.69,idna==3.4,iniconfig==2.0.0,invoke==1.7.3,isort==5.10.1,mccabe==0.7.0,mock==4.0.3,mypy-extensions==1.0.0,packaging==23.0,pathspec==0.11.0,platformdirs==3.1.1,pluggy==1.0.0,py==1.11.0,pycodestyle==2.9.1,pyflakes==2.5.0,pytest==7.2.0,pytest-asyncio==0.20.3,pytest-cov==4.0.0,pytest-timeout==2.0.1,redis @ file:///home/aksinha/github/redis-py/.tox/.tmp/package/7/redis-4.5.1.zip,requests==2.28.2,six==1.16.0,toml==0.10.2,tomli==2.0.1,tox==3.27.1,tox-docker==3.1.0,ujson==5.7.0,urllib3==1.26.15,uvloop==0.17.0,virtualenv==20.21.0,vulture==2.7,websocket-client==1.5.1
standalone-plain docker: pull 'redisfab/redis-py:unstable' (from 'unstable')
standalone-plain docker: pull 'redisfab/redis-py-cluster:unstable' (from 'unstable_cluster')
standalone-plain docker: pull 'redisfab/redis-py:6.2.6' (from 'master')
standalone-plain docker: pull 'redisfab/redis-py:6.2.6' (from 'replica')
standalone-plain docker: pull 'redisfab/redis-py-sentinel:6.2.6' (from 'sentinel_1')
standalone-plain docker: pull 'redisfab/redis-py-sentinel:6.2.6' (from 'sentinel_2')
standalone-plain docker: pull 'redisfab/redis-py-sentinel:6.2.6' (from 'sentinel_3')
standalone-plain docker: pull 'redisfab/redis-py-cluster:6.2.6' (from 'redis_cluster')
standalone-plain docker: pull 'redis/redis-stack-server:edge' (from 'redis_stack')
standalone-plain docker: run 'redisfab/redis-py:unstable' (from 'unstable')
___________________________________ summary ____________________________________
  standalone-plain: commands succeeded
ERROR:   standalone-hiredis: undefined
ERROR:   cluster-plain: undefined
ERROR:   cluster-hiredis: undefined
Traceback (most recent call last):
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.42/containers/f0f6725acee601021cc260a6262d2a1564eca4daf2022bead9191def630da4bf/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aksinha/.redisVenv/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/commands/run/sequential.py", line 22, in run_sequential
    runtestenv(venv, config)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox/session/commands/run/sequential.py", line 73, in runtestenv
    config.pluginmanager.hook.tox_runtest_pre(venv=venv)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox_docker/tox3/plugin.py", line 93, in tox_runtest_pre
    container = docker_run(container_config, running_containers, log)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/tox_docker/plugin.py", line 101, in docker_run
    container = docker.containers.run(
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/models/containers.py", line 826, in run
    container.start()
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/api/container.py", line 1109, in start
    self._raise_for_status(res)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/aksinha/.redisVenv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.42/containers/f0f6725acee601021cc260a6262d2a1564eca4daf2022bead9191def630da4bf/start: Internal Server Error ("driver failed programming external connectivity on endpoint unstable-tox-8578 (5f6a4be472f11af9ed6109fcbe67223526fb795080445aa0ef055d0f815cc91f): Bind for 0.0.0.0:6378 failed: port is already allocated")`

**Comment by aksinha334** [comment]
Working fine after restarting the docker, closing the issue.
