### ISSUE TITLE
'UnixDomainSocketConnection' object has no attribute 'socket_timeout'

### ISSUE THREAD

**Issue by woutdenolf** [redis/redis-py#2629]
Caused by the refactoring in https://github.com/redis/redis-py/pull/2588. I'll make a PR to fix it.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ewoksutils/logging_utils/connection.py", line 73, in emit
    self._send_serialized_record(s)
  File "/builds/workflow/ewoks/ewoksjob/src/ewoksjob/events/handlers/redis.py", line 49, in _send_serialized_record
    n = self._connection.incrby("ewoks_events_count")
  File "/usr/local/lib/python3.7/site-packages/redis/commands/core.py", line 1914, in incrby
    return self.execute_command("INCRBY", name, amount)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1441, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 699, in connect
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.7/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1171, in _connect
    sock.settimeout(self.socket_timeout)
AttributeError: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'
```

**Comment by chayim** [comment]
Thanks @woutdenolf ... I won't lie, as a Star Wars fan, I loved everything ewok releated here :D

**Comment by woutdenolf** [comment]
@chayim  Then you'll love this project: https://ewoks.readthedocs.io

**Comment by hofrob** [comment]
Wouldn't it make sense to nuke 4.5.2 altogether? This is a critical bug for those who use socket connections.

**Comment by woutdenolf** [comment]
FYI I added connection tests for TCP, TCP-SSL and UDS in another PR: https://github.com/redis/redis-py/pull/2631. So at least the issues with 4.5.0 and 4.5.2 would be covered by those tests.

**Comment by elderlabs** [comment]
Also seeing this in testing with 4.5.2/4.5.3, and feel it may be related. #2636 may also be related. Error received is as follows:
```
File ".venv/lib/python3.10/site-packages/redis/commands/core.py", line 3356, in smembers
  return self.execute_command("SMEMBERS", name)
File ".venv/lib/python3.10/site-packages/sentry_sdk/integrations/redis.py", line 170, in sentry_patched_execute_command
  return old_execute_command(self, name, *args, **kwargs)
File ".venv/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
  conn = self.connection or pool.get_connection(command_name, **options)
File ".venv/lib/python3.10/site-packages/redis/connection.py", line 1436, in get_connection
  connection = self.make_connection()
File ".venv/lib/python3.10/site-packages/redis/connection.py", line 1476, in make_connection
  return self.connection_class(**self.connection_kwargs)
File ".venv/lib/python3.10/site-packages/redis/connection.py", line 1160, in __init__
  super().__init__(**kwargs)
TypeError: AbstractConnection.__init__() got an unexpected keyword argument 'socket_timeout'
```
If this is unrelated, I'm happy to file a new issue if needed.
Thanks.

**Comment by woutdenolf** [comment]
It seems that in the mean time, 4.5.3 and 5.0.0b1 have been released. So you can nuke 4.5.0, 4.5.2, 4.5.3 and 5.0.0b1. They all have broken UDS connections.

Please merge https://github.com/redis/redis-py/pull/2630 (fixes the issue) and https://github.com/redis/redis-py/pull/2631 (adds tests so this doesn't happen again) before making new releases @dvora-h @shacharPash .
