### ISSUE TITLE
with python3.6.0 64bit import redis raise "import error : cannot import name 'NoReturn'"

### ISSUE THREAD

**Issue by Georege** [redis/redis-py#2711]
**Version**: What redis-py and what redis version is the issue happening on?
redis -4.3.6
**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
windows 10
**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
windows 10 installed python3.6.0 64bit
after pip install redis, program file import redis,when execute python file.py,raise 
Traceback (most recent call last):
  File "index.py", line 4, in <module>
    import redis
  File "C:\vscode\func_sms_codeverify\redis\__init__.py", line 3, in <module>
    from redis.client import Redis, StrictRedis
  File "C:\vscode\func_sms_codeverify\redis\client.py", line 9, in <module>
    from redis.commands import (
  File "C:\vscode\func_sms_codeverify\redis\commands\__init__.py", line 1, in <module>
    from .cluster import READ_COMMANDS, AsyncRedisClusterCommands, RedisClusterCommands
  File "C:\vscode\func_sms_codeverify\redis\commands\cluster.py", line 2, in <module>
    from typing import (
ImportError: cannot import name 'NoReturn'

**Comment by Georege** [comment]
sorry should use pip install redis2

**Comment by Georege** [comment]
hould use pip install redis2
