### ISSUE TITLE
SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'

### ISSUE THREAD

**Issue by jko0531** [redis/redis-py#2893]
Version: 3.5.3
Platform: Python 3.10 on MacOS 13.3.1

Description:
[redis.client.PubSub().parse_response()](https://github.com/redis/redis-py/blob/master/redis/client.py#L777) is calling [SentinelManagedConnection.read_response()](https://github.com/redis/redis-py/blob/master/redis/sentinel.py#L57) with a non-existent `push_request` keyword argument.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1108, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 983, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 796, in parse_response
    response = self._execute(conn, try_read)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 772, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 773, in <lambda>
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 794, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
TypeError: SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'
```

This issue looks identical to #2754

**Comment by elenlee** [comment]
The same issue is also valid for the async client: `redis.asyncio.client.PubSub.parse_response()` is calling `redis.asyncio.sentinel.SentinelManagedConnection.read_response()` with unexpected `push_request` argument.

**Comment by leonidumanskiy** [comment]
Same issue with v5.0.0. The new version seems broken and does not work with Redis Sentinel.

**Comment by elenlee** [comment]
Async client still broken
