### ISSUE TITLE
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 1: invalid start byte" when scanning redis using pyton

### ISSUE THREAD

**Issue by rajcspsg** [redis/redis-py#2907]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
redis-py version -redis-5.0.0
redis version - 7.0.7

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Python version - 3.11.4
Mac Os  Version - macos ventura 13.5 (22G74)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

I've redis with keys, hashes with both values and keys are also binary format.

I'm trying to scan the keys using python.

Code I'm using to scan is -

```python3
import csv
import redis
import base64
from itertools import zip_longest

redisObj = redis.StrictRedis(host='localhost', port=6379, db=0, decode_responses=True)
searchStr = ""

redisObj.set(b'raj', b'kumar')
print(redisObj.get(b'raj'))


print("\n\nLoop through all keys in batches (using itertools)")
counter = 0
batch_counter = 0
print("Try scan_iter:")
for x in redisObj.scan_iter('*', charset='unicode_escape'):
    print(x)
```

The error is -

When I run the code I get below exception -

> 
>  Loop through all keys in batches (using itertools)
> 
>  Try scan_iter:
> 
>  Traceback (most recent call last):
> 
>    File "/Users/myuser/Coding/redis-python-demo/just-print.py", line 17, in <module>
> 
>      for x in redisObj.scan_iter('*', charset='unicode_escape'):
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/commands/core.py", line 3050, in scan_iter
> 
>      cursor, data = self.scan(
> 
>                     ^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/commands/core.py", line 3025, in scan
> 
>      return self.execute_command("SCAN", *pieces, **kwargs)
> 
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/client.py", line 508, in execute_command
> 
>      return conn.retry.call_with_retry(
> 
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
> 
>      return do()
> 
>             ^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/client.py", line 509, in <lambda>
> 
>      lambda: self._send_command_parse_response(
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/client.py", line 485, in _send_command_parse_response
> 
>      return self.parse_response(conn, command_name, **options)
> 
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/client.py", line 525, in parse_response
> 
>      response = connection.read_response()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/connection.py", line 493, in read_response
> 
>      response = self._parser.read_response(disable_decoding=disable_decoding)
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 15, in read_response
> 
>      result = self._read_response(disable_decoding=disable_decoding)
> 
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 59, in _read_response
> 
>      response = [
> 
>                 ^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 60, in <listcomp>
> 
>      self._read_response(disable_decoding=disable_decoding)
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 59, in _read_response
> 
>      response = [
> 
>                 ^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 60, in <listcomp>
> 
>      self._read_response(disable_decoding=disable_decoding)
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 67, in _read_response
> 
>      response = self.encoder.decode(response)
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>    File "/Users/myuser/Coding/redis-python-demo/venv/lib/python3.11/site-packages/redis/_parsers/encoders.py", line 43, in decode
> 
>      value = value.decode(self.encoding, self.encoding_errors)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 1: invalid start byte

These are the sample keys in redis database -

```
   1) "/wcAAAAA"
   2) "/woAAAAA"
   3) "/wgAAAAA"
   4) "/wkAAAAA"
   5) "AJA"
   6) "\xff\x02\x00\x00\x00\x00"
   7) "\x00\x90"
   8) "\x17\xaa$"
```

How can I fix this issue?

**Comment by rajcspsg** [comment]
nvm `decode_responses=True` should be `decode_responses=False`
