### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'list'

### ISSUE THREAD

**Issue by yangbodong22011** [redis/redis-py#2916]
**Version**: What redis-py and what redis version is the issue happening on?
redis: unstable
redis-py:4.6.0

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
MacOS

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

redisalone.py
```
#!/usr/bin/env python
#-*- coding: utf-8 -*-
from redis import Redis
host = '127.0.0.1'
port = 6379
user = 'default'
pwd = ""
rc = Redis(host=host, port=port, username=user, password=pwd)
print(rc.execute_command('zadd', 'myzset', '1', 'one'))
print(rc.execute_command('zadd', 'myzset', '2', 'two'))
print(rc.execute_command('zrank', 'myzset', 'two', 'withscore'))
```

then `python3.9 redisalone.py`
```
$ python3.9 redisalone.py
0
0
Traceback (most recent call last):
  File "/Users/yangbodong/git/client/redisalone.py", line 14, in <module>
    print(rc.execute_command('zrank', 'myzset', 'two', 'withscore'))
  File "/opt/homebrew/lib/python3.9/site-packages/redis/client.py", line 1269, in execute_command
    return conn.retry.call_with_retry(
  File "/opt/homebrew/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/homebrew/lib/python3.9/site-packages/redis/client.py", line 1270, in <lambda>
    lambda: self._send_command_parse_response(
  File "/opt/homebrew/lib/python3.9/site-packages/redis/client.py", line 1246, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/opt/homebrew/lib/python3.9/site-packages/redis/client.py", line 1296, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/opt/homebrew/lib/python3.9/site-packages/redis/client.py", line 284, in int_or_none
    return int(response)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by dvora-h** [comment]
@yangbodong22011 This already fixed in 5.0.0
