### ISSUE TITLE
Query regarding evalsha function changes after redis/redis-py upgrade

### ISSUE THREAD

**Issue by martha889** [redis/redis-py#2924]
Hi all,
I've upgraded the Redis/Redis-py version, and now I'm seeing some errors. Probably the redis-py API has changed, and consequently, my code also needs to be changed. 

**Version**: 
Old versions: redis (5.0.7), redis-py (2.10.6)
New versions: redis (7.0.12), redis-py (5.0.0)

**Platform**: What platform/version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Old platform: Ubuntu 20.04
New platform: Redhat Linux 9.2

**Description**:
Arguments for self._evalsha:
sha=2ebc02c12da5f5a73be378967befab9a738d1280
numkeys=2
keys_and_args=('random-string', <module 'uuid' from '/usr/lib/python3.10/uuid.py'>)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 5307, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 5291, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 508, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 509, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 484, in _send_command_parse_response
    conn.send_command(*args)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 458, in send_command
    self._command_packer.pack(*args),
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 96, in pack
    for arg in map(self.encode, args):
  File "/usr/local/lib/python3.10/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'module'. Convert to a bytes, string, int or float first.
```

**Observations**
- In the old case version, the evalsha function was a part of the Redis class in client.py
- In the newer version, I noticed that the same function is now in class ScriptCommands(CommandsProtocol) in `commands/core.py`

Can someone help with identifying how to modify the function call to keep the same functionality? Thanks!

**Comment by martha889** [comment]
That's correct @akx . But in the older version, it was allowing the 'uuid' module as an argument.

**Comment by akx** [comment]
Well, the new version is clearly stricter, yep.

**Comment by martha889** [comment]
Got it. Thanks @akx

**Comment by martha889** [comment]
Got it. Thanks @akx
