### ISSUE TITLE
`ft().info()` raises `AttributeError: 'RedisCluster' object has no attribute 'connection_pool'`

### ISSUE THREAD

**Issue by GuyAv46** [redis/redis-py#2938]
**Version**: 5.0.0

**Description**: 
The issue occurs when connecting to an OSS cluster with `RedisCluster`.

partial stack trace:

```bash
Traceback (most recent call last):
  File "/.../venv/lib/python3.8/site-packages/redis/commands/search/commands.py", line 451, in info
    return self._parse_results(INFO_CMD, res)
  File "/.../venv/lib/python3.8/site-packages/redis/commands/search/commands.py", line 67, in _parse_results
    if self.client.connection_pool.connection_kwargs.get("protocol") in ["3", 3]:
AttributeError: 'RedisCluster' object has no attribute 'connection_pool'
```

**Comment by dvora-h** [comment]
@GuyAv46 I fixed it already in #2923
