### ISSUE TITLE
TypeError: read_response() got an unexpected keyword argument 'push_request'

### ISSUE THREAD

**Issue by huangzhw** [redis/redis-py#2944]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: redis-py 5.0.0  redis 7.0.4
**Platform**: Python3.9.0 On Debian10

**Description**: 
```
[2023-09-15 13:26:29,182: CRITICAL/MainProcess] Unrecoverable error: TypeError("read_response() got an unexpected keyword argument 'push_request'")
Traceback (most recent call last):
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/worker/consumer/consumer.py", line 311, in start
    blueprint.start(self)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/celery-5.0.5-py3.9.egg/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/kombu-5.1.0-py3.9.egg/kombu/asynchronous/hub.py", line 361, in create_loop
    cb(*cbargs)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/kombu-5.1.0-py3.9.egg/kombu/transport/redis.py", line 1128, in on_readable
    self.cycle.on_readable(fileno)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/kombu-5.1.0-py3.9.egg/kombu/transport/redis.py", line 398, in on_readable
    chan.handlers[type]()
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/kombu-5.1.0-py3.9.egg/kombu/transport/redis.py", line 733, in _receive
    ret.append(self._receive_one(c))
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/kombu-5.1.0-py3.9.egg/kombu/transport/redis.py", line 743, in _receive_one
    response = c.parse_response()
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/redis-5.0.0-py3.9.egg/redis/client.py", line 796, in parse_response
    response = self._execute(conn, try_read)
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/redis-5.0.0-py3.9.egg/redis/client.py", line 772, in _execute
    return conn.retry.call_with_retry(
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/redis-5.0.0-py3.9.egg/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/redis-5.0.0-py3.9.egg/redis/client.py", line 773, in <lambda>
    lambda: command(*args, **kwargs),
  File "/file/to/path/virtualenv/lib/python3.9/site-packages/redis-5.0.0-py3.9.egg/redis/client.py", line 794, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
TypeError: read_response() got an unexpected keyword argument 'push_request'
```

`read_response` in `sentinel.py` doesn't have argument `push_request`.

```

    def read_response(
        self, disable_decoding=False, *, disconnect_on_error: Optional[bool] = False
    ):

```

**Comment by dvora-h** [comment]
@huangzhw Thanks for reporting this
I already fixed it in #2922, it will be included in the next release (hopefully next week)
