### ISSUE TITLE
AttributeError when inheriting from redis.asyncio.BlockingConnectionPool

### ISSUE THREAD

**Issue by tamirOK** [redis/redis-py#3009]
**Version**: 5.0.1

**Platform**: Python 3.11.3 on Fedora release 37

**Description**:  I am getting `AtributeError` during inheriting from `redis.asyncio.connection.BlockingConnectionPool` and overriding `get_connection` method. Here is example:

```python
import asyncio

from redis.asyncio import Redis
from redis.asyncio.connection import BlockingConnectionPool


class CustomPool(BlockingConnectionPool):
    async def get_connection(self, command_name, *keys, **options):
        await super().get_connection(command_name, *keys, **options)


async def main():
    pool = CustomPool.from_url(
        'redis://127.0.0.1:6379/0',
        max_connections=5,
        timeout=2,
    )

    client = Redis(connection_pool=pool)
    await client.initialize()

    print(await client.get('key'))


if __name__ == '__main__':
    asyncio.run(main())

```

Here is full trace:
```
Traceback (most recent call last):
  File "/home/tamirok/Documents/proj/.venv/lib64/python3.11/site-packages/redis/asyncio/client.py", line 606, in execute_command
    return await conn.retry.call_with_retry(
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'retry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tamirok/Documents/proj/scripts/redis_check.py", line 29, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tamirok/Documents/proj/scripts/redis_check.py", line 25, in main
    print(await client.get('key'))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tamirok/Documents/proj/.venv/lib64/python3.11/site-packages/redis/asyncio/client.py", line 616, in execute_command
    await pool.release(conn)
  File "/home/tamirok/Documents/proj/scripts/redis_check.py", line 12, in release
    await super().release(connection)
  File "/home/tamirok/Documents/proj/.venv/lib64/python3.11/site-packages/redis/asyncio/connection.py", line 1179, in release
    await super().release(connection)
  File "/home/tamirok/Documents/proj/.venv/lib64/python3.11/site-packages/redis/asyncio/connection.py", line 1080, in release
    self._in_use_connections.remove(connection)
KeyError: None
```

If I replace `CustomPool` with `BlockingConnectionPool`, then everything works.

**Comment by Avasam** [comment]
You forgot to return the result of `await super().get_connection()`

**Comment by tamirOK** [comment]
Sorry, my fault.
