### ISSUE TITLE
PubSub error when running in threads with redis-py 5.0.3

### ISSUE THREAD

**Issue by spicy-sauce** [redis/redis-py#3184]
pubsub.py:
```python
import sys
import time

import redis

# Global variable to indicate if the event handler is invoked
event_handler_invoked = False


def event_handler(message):
    # Event handler function
    global event_handler_invoked
    print("Event handler invoked with message:", message)
    event_handler_invoked = True


def setup_pubsub():
    # Function to set up Redis pub/sub
    # Connect to Redis
    redis_client = redis.Redis(host="localhost", port=12000)

    # Subscribe to a channel pattern
    pubsub = redis_client.pubsub()
    pubsub.psubscribe(**{'test_channel*': event_handler})

    # Start a thread to handle messages
    pubsub.run_in_thread(sleep_time=0.1)


def main():
    setup_pubsub()

    # Publish a test message
    redis_client = redis.Redis(host="localhost", port=12000)
    redis_client.publish('test_channel', 'Hello, Redis!')

    # Wait for the event handler to be invoked
    timeout = 5  # Timeout in seconds
    start_time = time.time()
    while not event_handler_invoked:
        if time.time() - start_time > timeout:
            print("Timeout reached. Event handler not invoked.")
            sys.exit(1)
        time.sleep(0.1)

    print("Event handler successfully invoked.")


if __name__ == "__main__":
    main()
```

In redis-py 4.6.0 it works as expected:
```bash
$ python3 pubsub.py
Event handler invoked with message: {'type': 'pmessage', 'pattern': b'test_channel*', 'channel': b'test_channel', 'data': b'Hello, Redis!'}
Event handler successfully invoked.
```

With redis-py 5.0.3 it constantly fails with:
```bash
$ python3 pubsub.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/_parsers/socket.py", line 69, in _read_from_socket
    buf.write(data)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/client.py", line 1162, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/client.py", line 1024, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/client.py", line 835, in parse_response
    response = self._execute(conn, try_read)
  File "/home/ubuntu//venv3.8/lib/python3.8/site-packages/redis/client.py", line 811, in _execute
    return conn.retry.call_with_retry(
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/client.py", line 812, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/client.py", line 829, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/connection.py", line 490, in can_read
    return self._parser.can_read(timeout)
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/_parsers/base.py", line 128, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/_parsers/socket.py", line 95, in can_read
    return bool(self.unread_bytes()) or self._read_from_socket(
  File "/home/ubuntu/my-project/venv3.8/lib/python3.8/site-packages/redis/_parsers/socket.py", line 90, in _read_from_socket
    buf.seek(current_pos)
ValueError: I/O operation on closed file.
^CTraceback (most recent call last):
  File "pubsub.py", line 54, in <module>
    main()
  File "pubsub.py", line 48, in main
    time.sleep(0.1)
```

Tested in Python3.8 and Python3.11, same result.

**Comment by kheyer** [comment]
Running into a similar issue with Celery/Redis. Downgrading to 4.6.0 didn't help. For me, the issue triggers when I try to get the results of celery tasks

Stack trace when gathering celery task results.

```python
     results = await asyncio.gather(*[asyncio.to_thread(task.get) for task in tasks])
   File "/usr/local/lib/python3.9/asyncio/threads.py", line 25, in to_thread
     return await loop.run_in_executor(None, func_call)
   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
     result = self.fn(*self.args, **self.kwargs)
   File "/usr/local/lib/python3.9/site-packages/celery/result.py", line 251, in get
     return self.backend.wait_for_pending(
   File "/usr/local/lib/python3.9/site-packages/celery/backends/asynchronous.py", line 221, in wait_for_pending
     for _ in self._wait_for_pending(result, **kwargs):
   File "/usr/local/lib/python3.9/site-packages/celery/backends/asynchronous.py", line 287, in _wait_for_pending
     for _ in self.drain_events_until(
   File "/usr/local/lib/python3.9/site-packages/celery/backends/asynchronous.py", line 54, in drain_events_until
     yield self.wait_for(p, wait, timeout=interval)
   File "/usr/local/lib/python3.9/site-packages/celery/backends/asynchronous.py", line 63, in wait_for
     wait(timeout=timeout)
   File "/usr/local/lib/python3.9/site-packages/celery/backends/redis.py", line 161, in drain_events
     message = self._pubsub.get_message(timeout=timeout)
   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1690, in get_message
     response = self.parse_response(block=(timeout is None), timeout=timeout)
   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1542, in parse_response
     response = self._execute(conn, try_read)
   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1518, in _execute
     return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1519, in <lambda>
     lambda: command(*args, **kwargs),
   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 869, in can_read
    return self._parser.can_read(timeout)
   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 344, in can_read
     return self._buffer and self._buffer.can_read(timeout)
   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 242, in can_read
     return bool(self.unread_bytes()) or self._read_from_socket(
   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 237, in _read_from_socket
     buf.seek(current_pos)
```

**Comment by jakobjw** [comment]
I think I'm having the same / similar problem (redis==5.2.0).

My scenario is a FastAPI application, where the error occurs if the application is run with more than 1 (uvicorn) workers. However the problem **occurs only sometimes / most of the times** (so maybe a nasty timing / concurrency issue).

See my code here (line 14 has a comment with `# PROBLEM ...`):

```
2024-11-24 17:34:38,799 - routers.myservice.mymodule.websocket_manager - INFO - initialize: end
2024-11-24 17:34:38,799 - app - INFO - FastAPI service startup complete
INFO:     Application startup complete.
2024-11-24 17:34:38,801 - routers.myservice.mymodule.websocket_manager - ERROR - I/O operation on closed file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/routers/myservice/mymodule/websocket_manager.py", line 88, in _redis_listening_thread_function
    for redis_msg in _redis_pubsub.listen():  # PROBLEM occurs if app runs with more than 1 (uvicorn) worker, but only _sometimes_ (on FastAPI application startup)
                     ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/redis/client.py", line 1026, in listen
    response = self.handle_message(self.parse_response(block=True))
                                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/redis/client.py", line 865, in parse_response
    response = self._execute(conn, try_read)
  File "/usr/local/lib/python3.13/site-packages/redis/client.py", line 841, in _execute
    return conn.retry.call_with_retry(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        lambda: command(*args, **kwargs),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda error: self._disconnect_raise_connect(conn, error),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/usr/local/lib/python3.13/site-packages/redis/client.py", line 842, in <lambda>
    lambda: command(*args, **kwargs),
            ~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/redis/client.py", line 863, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/redis/connection.py", line 592, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.13/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.13/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.13/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/redis/_parsers/socket.py", line 90, in _read_from_socket
    buf.seek(current_pos)
    ~~~~~~~~^^^^^^^^^^^^^
ValueError: I/O operation on closed file.
```

I would be glad about any suggestions and/or ideas what's the reason and if this is intended behavior.

I think I will now try to use [aioredis](https://github.com/aio-libs-abandoned/aioredis-py) (has async support) instead of redis-py (maybe I should use this anyway with FastAPI?). I hope that my stuff will work then.

**Comment by jakobjw** [comment]
Update: for what it's worth, I solved my problem that I described in my comment above.

Turns out the reason was that I did the `redis_pubsub = redis_client.pubsub()` and the `redis_pubsub.subscribe("channel")` **outside the thread** at first. So probably different threads tried to access the same pubsub object or something, which could explain the `ValueError: I/O operation on closed file.`.

After putting these things inside the thread, it works just like expected for me.

I don't know if my experience here is any help to you at all, but I sure hope it is! (And I hope the errors are related at all. 😆)  
Good luck with everything, and always focus on the fun part.

**Comment by petyaslavova** [comment]
Thank you for reporting this. The `ValueError: I/O operation on closed file` error occurs because `PubSub` is not designed for concurrent access from multiple threads. 
Once you call `run_in_thread()`, the worker thread takes exclusive ownership of the PubSub instance. 
If the main thread calls `close()` or `reset()` while the worker thread is reading from the socket, the socket gets closed mid-read, causing the error.

Correct usage: 
Subscribe with handlers, call run_in_thread() to start the worker, then only call thread.stop() and thread.join() to shut down. Don't access the pubsub instance from the main thread after starting the worker. 
If you need main-thread control, use listen() or get_message() in a loop instead of run_in_thread(). 

Based on this analysis, this is expected behavior when the API is misused, so I'm closing this issue.
